import { defineConfig } from "@theholocron/cli";
import type { HolocronConfig } from "@theholocron/cli";
import { compose, nodeDocs, wikiCapability as wiki } from "@theholocron/holocron-config";

const { repo, workflows, providers, org, domain, docs } = compose(nodeDocs(), wiki());
export default defineConfig({
	description: "Shared configuration files.",
	homepage: "https://docs.theholocron.dev/configs/",
	org,
	domain,
	docs,
	repo: {
		teams: [{ slug: "gatekeepers", permission: "maintain" }],
		topics: [
			"browserslist-config",
			"commitlint-config",
			"developer-tools",
			"eslint-config",
			"lint-staged-config",
			"nodejs",
			"prettier-config",
			"semantic-release-config",
			"shareable-configs",
			"storybook-config",
			"stylelint-config",
			"tsconfig",
			"tsdown-config",
			"vite-config",
			"vitest-config",
		],
		...repo,
		requiredChecks: [
			...repo.requiredChecks,
			"codecov/project/astro-config",
			"codecov/project/browserslist-config",
			"codecov/project/commitlint-config",
			"codecov/project/devmoji-config",
			"codecov/project/eslint-config",
			"codecov/project/holocron-config",
			"codecov/project/lighthouse-config",
			"codecov/project/lint-staged-config",
			"codecov/project/prettier-config",
			"codecov/project/semantic-release-config",
			"codecov/project/storybook-config",
			"codecov/project/stylelint-config",
			"codecov/project/tsconfig",
			"codecov/project/tsdown-config",
			"codecov/project/vite-config",
			"codecov/project/vitest-config",
		],
	},
	workflows: [
		...workflows,
		"audit",
		{ name: "test", with: { "run-unit": true } },
		{ name: "release", with: { "run-build": true } },
		"sync",
	],
	providers: { ...providers, secrets: "github" },
	agent: "claude",
	skills: ["git-safety", "pr-workflow", "commit-standards", "security-review", "holocron-skill-config", "turborepo"],
} satisfies HolocronConfig);
