import type { HolocronConfig } from "@theholocron/cli";
import { defineConfig } from "@theholocron/cli";

export default defineConfig({
	description: "Shared configuration files.",
	homepage: "https://docs.theholocron.dev/configs/",
	org: "theholocron",
	domain: "theholocron.dev",
	docs: { build: "workflow", https: true },
	repo: {
		protection: "strict",
		properties: { lifecycle: "active", open_source: true, runtime_environment: "node", uses_external_packages: true },
		teams: [{ slug: "gatekeepers", permission: "maintain" }],
		topics: [
			"browserslist-config",
			"commitlint-config",
			"developer-tools",
			"eslint-config",
			"lint-staged-config",
			"nodejs",
			"prettier-config",
			"semantic-release-config",
			"shareable-configs",
			"storybook-config",
			"stylelint-config",
			"tsconfig",
			"tsdown-config",
			"vite-config",
			"vitest-config",
		],
	},
	tasks: [
		{ name: "sourceQuality.staticAnalysis", required: true },
		{ name: "sourceQuality.formatting", required: true },
		{ name: "sourceQuality.structuredDataValidation", required: true },
		{ name: "security.secretDetection", required: true },
		{ name: "platform.commitStandards", required: true },
		{ name: "verification.unitTests", required: true },
		"security.codeScanning",
		"review",
		"stale",
		"greetings",
		"dependencies",
		"bookkeeping",
		{ name: "verification.typeSafety", required: true },
		{ name: "knowledge.docs", with: { preview: true } },
		"knowledge.wiki",
	],
	extraRequiredChecks: [
		"codecov/patch",
		"codecov/project",
		"codecov/project/astro-config",
		"codecov/project/browserslist-config",
		"codecov/project/commitlint-config",
		"codecov/project/devmoji-config",
		"codecov/project/eslint-config",
		"codecov/project/holocron-config",
		"codecov/project/lighthouse-config",
		"codecov/project/lint-staged-config",
		"codecov/project/prettier-config",
		"codecov/project/semantic-release-config",
		"codecov/project/storybook-config",
		"codecov/project/stylelint-config",
		"codecov/project/tsconfig",
		"codecov/project/tsdown-config",
		"codecov/project/vite-config",
		"codecov/project/vitest-config",
	],
	providers: {
		source: "github",
		ci: "github",
		issues: ["github", { labels: { inProgress: "status:in-progress", inReview: "status:in-review" } }],
		secrets: "github",
		dns: "cloudflare",
		deployment: ["cloudflare", { accountId: "9c558af98664d13fc89b7e0a0d93d5a8" }],
		workers: ["cloudflare", { accountId: "9c558af98664d13fc89b7e0a0d93d5a8" }],
		wiki: ["fern", { domain: "wiki.theholocron.dev", fernOrg: "holocron", icon: "fa-duotone fa-sliders" }],
	},
	agent: "claude",
	skills: ["git-safety", "pr-workflow", "commit-standards", "security-review", "holocron-skill-config", "turborepo"],
} satisfies HolocronConfig);
